
services:
  first_container:  
    container_name: first_container
    hostname: first_container
    image: ssh_enabled
    command:
      - /bin/bash
      - -c 
      - | 
        echo -e "Sleeping to keep first_container up"
        sleep infinity;
    networks:
      container-net:
    depends_on:
      - second_container
      
  second_container:
    container_name: second_container
    hostname: second_container
    build:
      context: .
      dockerfile: Dockerfile
    image: ssh_enabled
    command:
      - /bin/bash
      - -c 
      - | 
        echo -e "Password update started"
        echo -e "${SECOND_CONTAINER_ROOT_PASSWORD:-CocaCola}\n${SECOND_CONTAINER_ROOT_PASSWORD:-CocaCola}" | passwd root;
        echo -e "Password update completed in second_container\n\nRestarting SSH"
        service ssh restart;
        echo -e "SSH restart completed\n\nSleeping to keep second_container up"
        sleep infinity;
    networks:
      container-net:  
    volumes:
      - ./ssh_configs/root_permission.conf:/etc/ssh/sshd_config.d/root_permission.conf
    ports:
      - 2222:22
        
networks:
  container-net:
    name: container-net
    driver: bridge