services:
  mongo-1:
    container_name: mongo-1
    image: mongo:8.2.3
    volumes:
      - ./data-files/data-1:/data/db
      - ./keys/goggles.key:/keys/goggles.key
    networks:
      mongo-net:
    ports:
      - 27017:27017
    restart: always    
    command:
      - /bin/sh
      - -c 
      - | 
        mongod --replSet goggle_rs --bind_ip_all --keyFile /keys/goggles.key;
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand('ping').ok","--quiet"]
      interval: 15s
      timeout: 10s
      retries: 6
      start_period: 30s
      
  mongo-2:
    container_name: mongo-2
    image: mongo:8.2.3
    volumes:
      - ./data-files/data-2:/data/db
      - ./keys/goggles.key:/keys/goggles.key
    networks:
      mongo-net:
    ports:
      - 27018:27017
    depends_on:
      mongo-1:
        condition: service_healthy     
    restart: always
    command:
      - /bin/sh
      - -c 
      - | 
        mongod --replSet goggle_rs --bind_ip_all --keyFile /keys/goggles.key;
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand('ping').ok","--quiet"]
      interval: 15s
      timeout: 10s
      retries: 6
      start_period: 60s        

      
  mongo-3:
    container_name: mongo-3
    image: mongo:8.2.3
    volumes:
      - ./data-files/data-3:/data/db
      - ./keys/goggles.key:/keys/goggles.key
    networks:
      mongo-net:
    ports:
      - 27019:27017
    depends_on:
      mongo-1:
        condition: service_healthy    
      mongo-2:
        condition: service_healthy
    restart: always
    command:
      - /bin/sh
      - -c 
      - | 
        mongod --replSet goggle_rs --bind_ip_all --keyFile /keys/goggles.key;
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand('ping').ok","--quiet"]
      interval: 15s
      timeout: 10s
      retries: 6
      start_period: 90s

  check-primary-available:
    container_name: check-rs-started
    image: mongo:8.2.3
    restart: no
    depends_on:
      mongo-1:
        condition: service_healthy      
      mongo-2:
        condition: service_healthy      
      mongo-3:
        condition: service_healthy
    command:    
      - /bin/sh
      - -c 
      - |
        mongosh --host mongo-1:27017 --eval "
           while (! db.isMaster().ismaster ) {
               print('Waiting for primary node mongo-1 to become available'); 
               sleep(1000);
           };
        ";
        echo "availability check completed";
    networks:
      mongo-net:
      
networks:
  mongo-net:
    name: mongo-net
    driver: bridge
