services:
  mongo-1:
    container_name: mongo-1
    image: mongo:8.2.3
    volumes:
      - ./data-files/data-1:/data/db
      - ./keys/goggles.key:/keys/goggles.key
    networks:
      mongo-net:
    ports:
      - 27017:27017
    depends_on:
      - mongo-2
    restart: always    
    command:
      - /bin/sh
      - -c 
      - | 
        mongod --replSet goggle_rs --bind_ip_all --keyFile /keys/goggles.key;

  mongo-2:
    container_name: mongo-2
    image: mongo:8.2.3
    volumes:
      - ./data-files/data-2:/data/db
      - ./keys/goggles.key:/keys/goggles.key
    networks:
      mongo-net:
    ports:
      - 27018:27017
    depends_on:
      - mongo-3      
    restart: always
    command:
      - /bin/sh
      - -c 
      - | 
        mongod --replSet goggle_rs --bind_ip_all --keyFile /keys/goggles.key;
        

      
  mongo-3:
    container_name: mongo-3
    image: mongo:8.2.3
    volumes:
      - ./data-files/data-3:/data/db
      - ./keys/goggles.key:/keys/goggles.key
    networks:
      mongo-net:
    ports:
      - 27019:27017
    restart: always
    command:
      - /bin/sh
      - -c 
      - | 
        mongod --replSet goggle_rs --bind_ip_all --keyFile /keys/goggles.key;

networks:
  mongo-net:
    name: mongo-net
    driver: bridge
