services:
  mongo-1:
    container_name: mongo-1
    image: mongo:8.2.3
    volumes:
      - ./data-files/data-1:/data/db
      - ./keys/goggles.key:/keys/goggles.key
    networks:
      mongo-net:
    ports:
      - 27017:27017
    restart: always    
    command:
      - /bin/sh
      - -c 
      - | 
        chown mongodb /keys/goggles.key;
        chmod 600 /keys/goggles.key;
        mongod --replSet goggle_rs --bind_ip_all;
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand('ping').ok","--quiet"]
      interval: 15s
      timeout: 10s
      retries: 6
      start_period: 30s
      
  mongo-2:
    container_name: mongo-2
    image: mongo:8.2.3
    volumes:
      - ./data-files/data-2:/data/db
    networks:
      mongo-net:
    ports:
      - 27018:27017
    depends_on:
      mongo-1:
        condition: service_healthy
    restart: always
    command:
      - /bin/sh
      - -c 
      - |         
        mongod --replSet goggle_rs --bind_ip_all;
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand('ping').ok","--quiet"]
      interval: 15s
      timeout: 10s
      retries: 6
      start_period: 60s

      
  mongo-3:
    container_name: mongo-3
    image: mongo:8.2.3
    volumes:
      - ./data-files/data-3:/data/db
    networks:
      mongo-net:
    ports:
      - 27019:27017
    depends_on:
      mongo-1:
        condition: service_healthy    
      mongo-2:
        condition: service_healthy
    restart: always
    command:
      - /bin/sh
      - -c 
      - | 
        mongod --replSet goggle_rs --bind_ip_all;
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand('ping').ok","--quiet"]
      interval: 15s
      timeout: 10s
      retries: 6
      start_period: 90s
      
      
  init-goggle-rs:
    container_name: init-goggle-rs
    image: mongo:8.2.3
    restart: no
    depends_on:
      mongo-1:
        condition: service_healthy      
      mongo-2:
        condition: service_healthy      
      mongo-3:
        condition: service_healthy
    command:    
      - /bin/sh
      - -c 
      - |
        mongosh --host mongo-1:27017 --eval "
            var rs_config = { 
              '_id': 'goggle_rs',
              'version': 1,
              'members': [
                {'_id': 0, 'host': 'mongo-1:27017', 'priority': 3},
                {'_id': 1, 'host': 'mongo-2:27017', 'priority': 2},
                {'_id': 2, 'host': 'mongo-3:27017', 'priority': 1}
               ]
            };
            rs.initiate(rs_config, { force: true });
            if (rs.status().ok){
                print('Replica-Set initialised successfully');
            }else{
                print('ERROR; Replica-Set initialisation failed');
            };
         ";
          
        sleep 5;
        
        mongosh --host mongo-1:27017 --eval "
           while (! db.isMaster().ismaster ) {
               print('Waiting for primary node mongo-1 to become available'); 
               sleep(1000);
           };
           print('Primary node mongo-1 successfully initialised and available');
            var usr_config = {
                'user' : '${MONGO_ADMIN_USER:-dbadmin}',
                 'pwd': '${MONGO_ADMIN_PASSWD:-password}',
                 'roles': [
                    {'role': 'userAdminAnyDatabase', 'db': 'admin'}, 
                    {'role': 'readWriteAnyDatabase', 'db': 'admin'}, 
                    {'role': 'dbAdminAnyDatabase'  , 'db': 'admin'}, 
                    {'role': 'clusterAdmin'        , 'db': 'admin'}
                ]
             };
            if(db.getSiblingDB('admin').createUser(usr_config).ok){
                print('user created successfully');
            }else{
                print('ERROR: user creation failed');
            };
        ";
    networks:
      mongo-net:

networks:
  mongo-net:
    name: mongo-net
    driver: bridge
