
services:
  first_container:
    image: ubuntu:latest
    container_name: first_container
    hostname: first_container
    command:
      - /bin/sh
      - -c 
      - | 
        sleep 5;
        apt -y update;
        apt -y upgrade;  
        apt -y install nano;
        apt -y install openssh-client;
        apt -y install openssh-server;        
        sleep infinity;
    networks:
      container-net:    
                    
  second_container:
    image: ubuntu:latest
    container_name: second_container
    hostname: second_container
    command:
      - /bin/sh
      - -c 
      - | 
        sleep 5;
        apt -y update;
        apt -y upgrade;  
        apt -y install nano;
        apt -y install openssh-client;
        apt -y install openssh-server;        
        sleep infinity;
    networks:
      container-net:  
        
networks:
  container-net:
    name: container-net
    driver: bridge